
struct SampleProfiles {
    static var items: [[String: Any]] = [
        ["age": 21, "country": "Japan", "city": "Kyoto", "bio": "Bio1".localize()],
        ["age": 42, "country": "Czech Republic", "city": "Prague", "bio": "Bio2".localize()],
        ["age": 19, "country": "USA", "city": "LA", "bio": "Bio3".localize()],
        ["age": 22, "country": "Italy", "city": "Milan", "bio": "Bio4".localize()],
        ["age": 20, "country": "South Korea", "city": "Seoul", "bio": "Bio5".localize()],
        ["age": 23, "country": "Spain", "city": "Barcelona", "bio": "Bio6".localize()],
        ["age": 52, "country": "Austria", "city": "Salzburg", "bio": "Bio7".localize()],
        ["age": 21, "country": "Canada", "city": "Toronto", "bio": "Bio8".localize()],
        ["age": 24, "country": "USA", "city": "Boston", "bio": "Bio9".localize()],
        ["age": 19, "country": "Germany", "city": "Berlin", "bio": "Bio10".localize()],
        ["age": 22, "country": "Mexico", "city": "Guadalajara", "bio": "Bio11".localize()],
        ["age": 20, "country": "USA", "city": "New York", "bio": "Bio12".localize()],
        ["age": 23, "country": "UAE", "city": "Dubai", "bio": "Bio13".localize()],
        ["age": 21, "country": "France", "city": "Paris", "bio": "Bio14".localize()],
        ["age": 39, "country": "Italy", "city": "Florence", "bio": "Bio15".localize()],
        ["age": 22, "country": "UK", "city": "London", "bio": "Bio16".localize()],
        ["age": 19, "country": "South Korea", "city": "Busan", "bio": "Bio17".localize()],
        ["age": 20, "country": "USA", "city": "Miami", "bio": "Bio18".localize()],
        ["age": 24, "country": "Australia", "city": "Sydney", "bio": "Bio19".localize()],
        ["age": 22, "country": "Italy", "city": "Rome", "bio": "Bio20".localize()],
        ["age": 19, "country": "USA", "city": "Chicago", "bio": "Bio21".localize()],
        ["age": 23, "country": "Mexico", "city": "Cancun", "bio": "Bio22".localize()],
        ["age": 21, "country": "Brazil", "city": "Rio", "bio": "Bio23".localize()],
        ["age": 44, "country": "France", "city": "Lyon", "bio": "Bio24".localize()],
        ["age": 20, "country": "Japan", "city": "Tokyo", "bio": "Bio25".localize()],
        ["age": 21, "country": "USA", "city": "San Francisco", "bio": "Bio26".localize()],
        ["age": 22, "country": "Turkey", "city": "Istanbul", "bio": "Bio27".localize()],
        ["age": 19, "country": "Russia", "city": "Moscow", "bio": "Bio28".localize()],
        ["age": 20, "country": "India", "city": "Delhi", "bio": "Bio29".localize()],
        ["age": 23, "country": "Argentina", "city": "Buenos Aires", "bio": "Bio30".localize()],
        ["age": 20, "country": "USA", "city": "Austin", "bio": "Bio31".localize()],
        ["age": 48, "country": "Germany", "city": "Hamburg", "bio": "Bio32".localize()],
        ["age": 19, "country": "USA", "city": "Dallas", "bio": "Bio33".localize()],
        ["age": 20, "country": "Canada", "city": "Vancouver", "bio": "Bio34".localize()],
        ["age": 23, "country": "USA", "city": "Las Vegas", "bio": "Bio35".localize()],
        ["age": 21, "country": "Spain", "city": "Madrid", "bio": "Bio36".localize()],
        ["age": 19, "country": "France", "city": "Nice", "bio": "Bio37".localize()],
        ["age": 22, "country": "Germany", "city": "Munich", "bio": "Bio38".localize()],
        ["age": 20, "country": "Brazil", "city": "São Paulo", "bio": "Bio39".localize()],
        ["age": 21, "country": "Japan", "city": "Osaka", "bio": "Bio40".localize()],
        ["age": 23, "country": "Mexico", "city": "Mexico City", "bio": "Bio41".localize()],
        ["age": 21, "country": "Brazil", "city": "Salvador", "bio": "Bio42".localize()],
        ["age": 19, "country": "Argentina", "city": "Cordoba", "bio": "Bio43".localize()],
        ["age": 22, "country": "Poland", "city": "Warsaw", "bio": "Bio44".localize()],
        ["age": 21, "country": "Sweden", "city": "Stockholm", "bio": "Bio45".localize()],
        ["age": 20, "country": "Norway", "city": "Oslo", "bio": "Bio46".localize()],
        ["age": 23, "country": "Netherlands", "city": "Amsterdam", "bio": "Bio47".localize()],
        ["age": 22, "country": "India", "city": "Bangalore", "bio": "Bio48".localize()],
        ["age": 19, "country": "Switzerland", "city": "Zurich", "bio": "Bio49".localize()],
        ["age": 24, "country": "Austria", "city": "Vienna", "bio": "Bio50".localize()],
        ["age": 20, "country": "India", "city": "Mumbai", "bio": "Bio51".localize()],
        ["age": 22, "country": "China", "city": "Beijing", "bio": "Bio52".localize()],
        ["age": 24, "country": "Morocco", "city": "Casablanca", "bio": "Bio53".localize()],
        ["age": 21, "country": "South Africa", "city": "Cape Town", "bio": "Bio54".localize()],
        ["age": 23, "country": "Greece", "city": "Athens", "bio": "Bio55".localize()],
        ["age": 19, "country": "Portugal", "city": "Lisbon", "bio": "Bio56".localize()],
        ["age": 24, "country": "Egypt", "city": "Cairo", "bio": "Bio57".localize()]
    ]
}
