//
//  FeedVM.swift
//  ChatBot20
//
//  Created by Mikita on 06/07/2026.
//

import Foundation

class FeedVM {
    
    // Исходные базы данных видео
    let friendsPool: [String] = [
        "https://youtube.com/shorts/74FasD2jDGg?feature=share",
        "https://youtube.com/shorts/tPLlRVd-9zk?feature=share",
        "https://youtube.com/shorts/ybFHEk1A7Qc?feature=share",
        "https://youtube.com/shorts/zN5u-XM4-Is?feature=share",
        "https://youtube.com/shorts/duaVJHY5iFs?feature=share",
        "https://youtube.com/shorts/hTkb7LxMHKU?feature=share",
        "https://youtube.com/shorts/CIfmUVCPml4?feature=share",
        "https://youtube.com/shorts/hoR2dPiNkdU?feature=share",
        "https://youtube.com/shorts/CVwL9yowgGA?feature=share",
        "https://youtube.com/shorts/LFYCg2kAJjA?feature=share",
        "https://youtube.com/shorts/1j7lofY9JP8?feature=share",
        "https://youtube.com/shorts/92pH8SN3ooM?feature=share",
        "https://youtube.com/shorts/bn98rraTUIs?feature=share",
        "https://youtube.com/shorts/5snYxEKIqdg?feature=share",
        "https://youtube.com/shorts/G-GmrGjtJmA?feature=share",
        "https://youtube.com/shorts/9IEtxVe577s?feature=share",
        "https://youtube.com/shorts/qFxIauXGoJY?feature=share",
        "https://youtube.com/shorts/ILLulNS9udE?feature=share",
        "https://youtube.com/shorts/2pXnHiwDrYI?feature=share",
        "https://youtube.com/shorts/XCJHD2emj1w?feature=share",
        "https://youtube.com/shorts/rp8K2Paf3PI?feature=share",
        "https://youtube.com/shorts/J-lnoihB2o8?feature=share",
        "https://youtube.com/shorts/Dg3DgCd3hps?feature=share",
        "https://youtube.com/shorts/aBrHA9PJ_AI?feature=share",
        "https://youtube.com/shorts/awCRyfzUpB4?feature=share",
        "https://youtube.com/shorts/zKKu4F153VU?feature=share",//
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
    
    let feedPool: [String] = [
        "https://www.youtube.com/shorts/v6uT6kdXxkA", "https://www.youtube.com/shorts/BOqrg_61v5U",
        "https://www.youtube.com/shorts/ZUhHQSpzABc", "https://www.youtube.com/shorts/FzgBPkfQm2I",
        "https://www.youtube.com/shorts/H4_hxjgfq9w", "https://www.youtube.com/shorts/YcRgHirjwYg",
        "https://www.youtube.com/shorts/BeJ-lab2Mks",
        "https://www.youtube.com/shorts/qPfjsncfIjs", "https://www.youtube.com/shorts/yUJf0qX9vEA",
        "https://www.youtube.com/shorts/U1prwI3WF1Q", "https://www.youtube.com/shorts/0xisq2NFnE8",
        "https://www.youtube.com/shorts/wjS0ZEP6X3Q", "https://www.youtube.com/shorts/g1PatgIMcrg",
        "https://www.youtube.com/shorts/LVaWa6_KgU4", "https://www.youtube.com/shorts/11mTRkCdIJ0",
        "https://www.youtube.com/shorts/m9XM-tCNDwo", "https://www.youtube.com/shorts/NYTqgwHRk78",
        "https://www.youtube.com/shorts/SnXewndv5cU", "https://www.youtube.com/shorts/noapALzLnDM",
        "https://www.youtube.com/shorts/tx5-stJkwY4", "https://www.youtube.com/shorts/ejMVniS_1Eo",
        "https://www.youtube.com/shorts/2-kwxBtNlV4", "https://www.youtube.com/shorts/f3lHPvknrTs",
        "https://www.youtube.com/shorts/x023rhUfgVs", "https://www.youtube.com/shorts/nxX9cTvnZxs",
        "https://www.youtube.com/shorts/3KYnDSQojP0", "https://www.youtube.com/shorts/luSgaddKBXc",
        "https://www.youtube.com/shorts/-O2qKdvwr5w", "https://www.youtube.com/shorts/EasH1kOZxZ0",
        "https://www.youtube.com/shorts/Y2GAx5bo7Bs", "https://www.youtube.com/shorts/N9k4oi6kN8Y",
        "https://www.youtube.com/shorts/vG-oU7OSOOw", "https://www.youtube.com/shorts/FeuH0jcUxHQ",
        "https://www.youtube.com/shorts/KIqnjC1UvdE", "https://www.youtube.com/shorts/yME-Emqd6-s",
        "https://www.youtube.com/shorts/WkVfrVISi6A", "https://www.youtube.com/shorts/UjwPdqg8r2Y",
        "https://www.youtube.com/shorts/A-TXMdWA8BM", "https://www.youtube.com/shorts/_1FERZD7YWk",
        "https://www.youtube.com/shorts/Ret7FGnoITU", "https://www.youtube.com/shorts/M4-P0u22BOc",
        "https://www.youtube.com/shorts/3vGDWv5S8qk", "https://www.youtube.com/shorts/aPyyHHiykEw",
        "https://www.youtube.com/shorts/3MBSfg_NTKk", "https://www.youtube.com/shorts/eYddOS7krMI",
        "https://www.youtube.com/shorts/LAknEx2ykmo", "https://www.youtube.com/shorts/PRGXnvtetPk",
        "https://www.youtube.com/shorts/sUazr6jYlNY", "https://www.youtube.com/shorts/Y-WtsvjLbJI",
        "https://www.youtube.com/shorts/oeEpohotttI", "https://www.youtube.com/shorts/kT7oPjYD0PQ",
        "https://www.youtube.com/shorts/9UME1-qMcWc", "https://www.youtube.com/shorts/Hy3yzEUALvU",
        "https://www.youtube.com/shorts/1YadsVbvXro", "https://www.youtube.com/shorts/Ry0tCeZZQeg",
        "https://www.youtube.com/shorts/DddXzv1VED8", "https://www.youtube.com/shorts/aJeTepHqC1w",
        "https://www.youtube.com/shorts/xeUqTwKc4Ag", "https://www.youtube.com/shorts/LbuCY3ghYkY",
        "https://www.youtube.com/shorts/WfHDNr1Fwxs", "https://www.youtube.com/shorts/3IGOPixn8Uw",
        "https://www.youtube.com/shorts/Dwde9wenC3E", "https://www.youtube.com/shorts/zOSDr1Qu_Og",
        "https://www.youtube.com/shorts/WTODM_sqgvM", "https://www.youtube.com/shorts/BYTrB7f20OU",
        "https://www.youtube.com/shorts/81YfUTO8Eoc", "https://www.youtube.com/shorts/doqiaX3vfHE",
        "https://www.youtube.com/shorts/nEq_fj_4UgY", "https://www.youtube.com/shorts/iaOtj2fO1Wk",
        "https://www.youtube.com/shorts/HFaxvFOHcJw", "https://www.youtube.com/shorts/2-rJ3hXUihY",
        "https://www.youtube.com/shorts/qXv1z_LFM3U", "https://www.youtube.com/shorts/mFH7hE4hP60",
        "https://www.youtube.com/shorts/m7vHAynI24Y", "https://www.youtube.com/shorts/vRQzXwUKKrI",
        "https://www.youtube.com/shorts/nfbS9McMOBQ", "https://www.youtube.com/shorts/3vdt7O4BGME",
        "https://www.youtube.com/shorts/nO0OgdVn5Tw", "https://www.youtube.com/shorts/7kgVsuGg9K8",
        "https://www.youtube.com/shorts/nEaRx0LQk64", "https://www.youtube.com/shorts/aHvu9CI2Lww",
        "https://www.youtube.com/shorts/UdUUMD9KBXY", "https://www.youtube.com/shorts/F8A-9S7vh0g",
        "https://www.youtube.com/shorts/wCAh3ck6EVo", "https://www.youtube.com/shorts/xyLaXFVxkXs",
        "https://www.youtube.com/shorts/swrgASGVLgY", "https://www.youtube.com/shorts/vMvavBsbcVY",
        "https://www.youtube.com/shorts/DZp8Jh1a9-Y", "https://www.youtube.com/shorts/jm_NQ_J_pPY",
        "https://www.youtube.com/shorts/3uxFzNeKOVw", "https://www.youtube.com/shorts/61LbSctEnb8",
        "https://www.youtube.com/shorts/inGhNmV2fFw", "https://www.youtube.com/shorts/4QHeFot9zfU",
        "https://www.youtube.com/shorts/P_wPYBOdyWo", "https://www.youtube.com/shorts/JdoHQwb-4ck",
        "https://www.youtube.com/shorts/N3cT3l9olxY", "https://www.youtube.com/shorts/eMOUXIISuq4",
        "https://www.youtube.com/shorts/oAPWfIqKU5A", "https://www.youtube.com/shorts/KXfQLfbTUoo",
        "https://www.youtube.com/shorts/dSp8xMlwjuc", "https://www.youtube.com/shorts/swIVhYjj1G8",
        "https://www.youtube.com/shorts/w24OVukbpso", "https://www.youtube.com/shorts/hzQux59MH_M",
        "https://www.youtube.com/shorts/saNdUWkYT08", "https://www.youtube.com/shorts/d4hVgYSm03w",
        "https://www.youtube.com/shorts/2TSOju2gbQ0", "https://www.youtube.com/shorts/dq8spTbwSJY",
        "https://www.youtube.com/shorts/b4Usrtkdb_s", "https://www.youtube.com/shorts/pZxsfb_TjvM",
        "https://www.youtube.com/shorts/1VGNtf1t45s", "https://www.youtube.com/shorts/sHWRsKENvac",
        "https://www.youtube.com/shorts/MJWQHvVqR60", "https://www.youtube.com/shorts/abTwPplx15Q",
        "https://www.youtube.com/shorts/s7lduFALIFA", "https://www.youtube.com/shorts/CkP7uEowmCY",
        "https://www.youtube.com/shorts/JWAxCDoWWE0", "https://www.youtube.com/shorts/y9Xnv_llADE",
        "https://www.youtube.com/shorts/X2sbtiS8W_A", "https://www.youtube.com/shorts/tg4xc5arrxU",
        "https://www.youtube.com/shorts/gWVwHeviYhg", "https://www.youtube.com/shorts/8jZb_F-AxMA",
        "https://www.youtube.com/shorts/j_oIU69qtdI", "https://www.youtube.com/shorts/Bf1pR5ioCKo",
        "https://www.youtube.com/shorts/u8F1SZNkmAU", "https://www.youtube.com/shorts/XSgYzWvQrlc",
        "https://www.youtube.com/shorts/TTJhohxAyhk", "https://www.youtube.com/shorts/dXlEZs8ld4Y",
        "https://www.youtube.com/shorts/9Vh43liK6cw", "https://www.youtube.com/shorts/TVz4WSNdYno",
        "https://www.youtube.com/shorts/ges18OJNpHs", "https://www.youtube.com/shorts/0b7-OqL0AeE",
        "https://www.youtube.com/shorts/GamqN69o9f0", "https://www.youtube.com/shorts/1Xemn2pibZE",
        "https://www.youtube.com/shorts/4HvPYodr7Kc", "https://www.youtube.com/shorts/coghr_Tsu6w",
        "https://www.youtube.com/shorts/r3lh5bj6mwE", "https://www.youtube.com/shorts/-uX8wFhjEiw",
        "https://www.youtube.com/shorts/ZGHfQFhiSqI", "https://www.youtube.com/shorts/kxI5c4nySOg",
        "https://www.youtube.com/shorts/oPRlojuKaGw", "https://www.youtube.com/shorts/WBP8HNEKXkA",
        "https://www.youtube.com/shorts/V_DBEW5vg_E", "https://www.youtube.com/shorts/kcyGoJdn7CA",
        "https://www.youtube.com/shorts/y5-9FKBTc64", "https://www.youtube.com/shorts/FZe9WgAcqCE",
        "https://www.youtube.com/shorts/InrQBYpCfkE", "https://www.youtube.com/shorts/NA6i5JZ6lWk",
        "https://www.youtube.com/shorts/jqNjZsb2P1c", "https://www.youtube.com/shorts/tHtjI35S2Cg",
        "https://www.youtube.com/shorts/qohR6aLDjVM", "https://www.youtube.com/shorts/yNV2bcy4MXM",
        "https://www.youtube.com/shorts/rJ10wFZ8OzU", "https://www.youtube.com/shorts/ly9a8BZ4oIE",
        "https://www.youtube.com/shorts/WQ3rzwYgKM4", "https://www.youtube.com/shorts/Sf0MHXEzJSY",
        "https://www.youtube.com/shorts/Ax7JzewSGbs", "https://www.youtube.com/shorts/Yf0c2SOJS70",
        "https://www.youtube.com/shorts/HhwzJzwcfoA", "https://www.youtube.com/shorts/KFYBEWYxfv0",
        "https://www.youtube.com/shorts/vgX7bqaV_bw", "https://www.youtube.com/shorts/F2O61a_1Hx0",
        "https://www.youtube.com/shorts/iRd6jLTgpn0", "https://www.youtube.com/shorts/h9AgnX8QOj8",
        "https://www.youtube.com/shorts/TA0DB1ZUtPs", "https://www.youtube.com/shorts/B7GujuaO-Vs",
        "https://www.youtube.com/shorts/YYlhmTK_Y5s", "https://www.youtube.com/shorts/ZCcFzZVPJ6I",
        "https://www.youtube.com/shorts/GSWaTgyF2EI", "https://www.youtube.com/shorts/AiovgRO2qmY",
        "https://www.youtube.com/shorts/qQck60xE4Co", "https://www.youtube.com/shorts/Ab4EmnH1OHw",
        "https://www.youtube.com/shorts/c8vDhm6SS7c", "https://www.youtube.com/shorts/-p3cAGKQslE",
        "https://www.youtube.com/shorts/CaDRNvWjdC8", "https://www.youtube.com/shorts/bCk_2w6NuOE",
        "https://www.youtube.com/shorts/mSkuq_RjcwM", "https://www.youtube.com/shorts/6lEi48DsAQY",
        "https://www.youtube.com/shorts/J1VIZcRaaNA", "https://www.youtube.com/shorts/WpmjmrYRIx4",
        "https://www.youtube.com/shorts/UPnIGR3QluY", "https://www.youtube.com/shorts/FgC66MVNb3E",
        "https://www.youtube.com/shorts/Ejfooadp1es", "https://www.youtube.com/shorts/_EXevKLapwo",
        "https://www.youtube.com/shorts/SD1EhnF_MM4", "https://www.youtube.com/shorts/bbtuszD2484",
        "https://www.youtube.com/shorts/mrZJgtBmgJQ", "https://www.youtube.com/shorts/g5zFfGE9XWY",
        "https://www.youtube.com/shorts/AgkNzdXdLek", "https://www.youtube.com/shorts/kU2nngdNQq8",
        "https://www.youtube.com/shorts/rPlXOvHpAyY", "https://www.youtube.com/shorts/rmI2ubMHCbU",
        "https://www.youtube.com/shorts/3df7yHX3ePo", "https://www.youtube.com/shorts/clXNz8AA-dg",
        "https://www.youtube.com/shorts/Lj0vp5DvYx4", "https://www.youtube.com/shorts/Q-gIawVdzNU",
        "https://www.youtube.com/shorts/9xAZVkbGBAI", "https://www.youtube.com/shorts/0KPciC5DO3Q",
        "https://www.youtube.com/shorts/jux6GXLroGA", "https://www.youtube.com/shorts/S1ZK2W3p2Rc",
        "https://www.youtube.com/shorts/ZLqoXPOjirA", "https://www.youtube.com/shorts/tFemKlHvYK4",
        "https://www.youtube.com/shorts/btyYe-W_DHE", "https://www.youtube.com/shorts/u7IQVZe56qk",
        "https://www.youtube.com/shorts/Z9vS2cu9LY8", "https://www.youtube.com/shorts/7aHywi_4Ktg",
        "https://www.youtube.com/shorts/_fS601XAMdQ", "https://www.youtube.com/shorts/U3qjCfWXFwg",
        "https://www.youtube.com/shorts/lvPZxIOI3W8", "https://www.youtube.com/shorts/fKhHhaYkDck",
        "https://www.youtube.com/shorts/k4WBPCuON7g", "https://www.youtube.com/shorts/rCFWmvcCdSQ",
        "https://www.youtube.com/shorts/onPmlqrrDQg", "https://www.youtube.com/shorts/g9lNw8rQlAE",
        "https://www.youtube.com/shorts/ylwuuO0yQxU", "https://www.youtube.com/shorts/DFt1iixqL4o",
        "https://www.youtube.com/shorts/6-hi3i32ZXg", "https://www.youtube.com/shorts/DxaJmohlXLs",
        "https://www.youtube.com/shorts/eJdp3zy29z0", "https://www.youtube.com/shorts/deky3SDn2rA",
        "https://www.youtube.com/shorts/dM98Ml83Y7o", "https://www.youtube.com/shorts/ea0CFVZxOmA",
        "https://www.youtube.com/shorts/Atia1-cfV18", "https://www.youtube.com/shorts/o-whZO_3-wo",
        "https://www.youtube.com/shorts/45xgUE3W24I", "https://www.youtube.com/shorts/VUBjNcGCpfs",
        "https://www.youtube.com/shorts/9Vh43liK6cw", "https://www.youtube.com/shorts/WjBvxhTGTKQ",
        "https://www.youtube.com/shorts/i0P-BM6ILyM", "https://www.youtube.com/shorts/PTPtvlvEcHA",
        "https://www.youtube.com/shorts/dLbULNaWAzg", "https://www.youtube.com/shorts/J9VzIA8EqP8",
        "https://www.youtube.com/shorts/onOycS3IklY", "https://www.youtube.com/shorts/p2yeEJARgfQ",
        "https://www.youtube.com/shorts/Ar3uavt0BbY", "https://www.youtube.com/shorts/o7Nec__excY",
        "https://www.youtube.com/shorts/OwWEvJ0kOzo", "https://www.youtube.com/shorts/5MLBReNwK6o",
        "https://www.youtube.com/shorts/VrzFRUhaUdo", "https://www.youtube.com/shorts/QlBoKoAnPW0",
        "https://www.youtube.com/shorts/0wouwNgc-j8", "https://www.youtube.com/shorts/biytb8q5fPU",
        "https://www.youtube.com/shorts/uGFA5KCrFjI", "https://www.youtube.com/shorts/LY_E0voXO-c",
        "https://www.youtube.com/shorts/wA5_DYEXfCA", "https://www.youtube.com/shorts/1cpky-jJtMw",
        "https://www.youtube.com/shorts/abATQPt8xA4", "https://www.youtube.com/shorts/XPR-ghBlmEo",
        "https://www.youtube.com/shorts/-0WkdS5lBeI", "https://www.youtube.com/shorts/JO5UTi9QDVo",
        "https://www.youtube.com/shorts/TBHFZ_caWeU", "https://www.youtube.com/shorts/Nkj75HMigDQ",
        "https://www.youtube.com/shorts/rAbgC4HCw6A", "https://www.youtube.com/shorts/gTGaCq7X5So",
        "https://www.youtube.com/shorts/f95k8TN2I6g", "https://www.youtube.com/shorts/Pat2cM-nYX4",
        "https://www.youtube.com/shorts/WYeeo9CgE_g", "https://www.youtube.com/shorts/4fU0ut6JOPQ",
        "https://www.youtube.com/shorts/UcqjkP3fQrQ", "https://www.youtube.com/shorts/txzl_2kuSWQ",
        "https://www.youtube.com/shorts/rJi2WK8PQoo", "https://www.youtube.com/shorts/78AxByrb2ek",
        "https://www.youtube.com/shorts/w2k1FTOGsnc", "https://www.youtube.com/shorts/IqKbwG5t3BU",
        "https://www.youtube.com/shorts/ajDrrjt5KpI", "https://www.youtube.com/shorts/Bf1pR5ioCKo",
        "https://www.youtube.com/shorts/5bcMVNvaSic", "https://www.youtube.com/shorts/NHBxhxFj1sg",
        "https://www.youtube.com/shorts/6HU_nsHTVzQ", "https://www.youtube.com/shorts/j27GZW-0TDU",
        "https://www.youtube.com/shorts/FPBTW4qhAXs", "https://www.youtube.com/shorts/bSmIQ3dVt2w",
        "https://www.youtube.com/shorts/pMGryND1uJA", "https://www.youtube.com/shorts/qO9I7x_yb3U",
        "https://www.youtube.com/shorts/qK_fskblDks", "https://www.youtube.com/shorts/8yxFVYHivtA",
        "https://www.youtube.com/shorts/YI1hhc0gSgw", "https://www.youtube.com/shorts/SIpr5mTx3Pk",
        "https://www.youtube.com/shorts/ZIdexLwG9vA", "https://www.youtube.com/shorts/ZVaFFHxgtNc",
        "https://www.youtube.com/shorts/BzBbqDt0Jx8", "https://www.youtube.com/shorts/3WjY7R3QTnA",
        "https://www.youtube.com/shorts/w-1fE_KMTWI", "https://www.youtube.com/shorts/yDBvnROQTlw",
        "https://www.youtube.com/shorts/NSb7fbZ8Q2A", "https://www.youtube.com/shorts/6ABSU0Fzk5c",
        "https://www.youtube.com/shorts/95oIiy0D2qI", "https://www.youtube.com/shorts/sRzqRXxaKLc",
        "https://www.youtube.com/shorts/iF8QVOwef4o", "https://www.youtube.com/shorts/CiRbF7dSOUY",
        "https://www.youtube.com/shorts/37rXC-YXjPQ", "https://www.youtube.com/shorts/l2KiEwYDu_8",
        "https://www.youtube.com/shorts/Ls9oWxGfBvw", "https://www.youtube.com/shorts/mbskVt14-Cw",
        "https://www.youtube.com/shorts/3DxTZ2inHOY", "https://www.youtube.com/shorts/Ql5IOpW8REo",
        "https://www.youtube.com/shorts/FxQ5kOnaTCE", "https://www.youtube.com/shorts/jdmGCK8ag8w",
        "https://www.youtube.com/shorts/zlBPCvumfYE", "https://www.youtube.com/shorts/h7-8020A9nU",
        "https://www.youtube.com/shorts/S3NRX6kgILA", "https://www.youtube.com/shorts/mpKg08VU7l8",
        "https://www.youtube.com/shorts/u5HHQDRS7Ic", "https://www.youtube.com/shorts/8GqVKQ1YJuc",
        "https://www.youtube.com/shorts/h15ORf5Tces", "https://www.youtube.com/shorts/BnwGv4c7VDA",
        "https://www.youtube.com/shorts/X7HaliUwG4w", "https://www.youtube.com/shorts/JDN-ODkLi0k",
        "https://www.youtube.com/shorts/fbFuCqb5e9U", "https://www.youtube.com/shorts/wAtBiXbJHZE",
        "https://www.youtube.com/shorts/J9d0NYIuYKk", "https://www.youtube.com/shorts/zqOEmtcSYUE",
        "https://www.youtube.com/shorts/sJoGob7TnGs", "https://www.youtube.com/shorts/huX0AmqD93A",
        "https://www.youtube.com/shorts/wJQuhtSq8Ms", "https://www.youtube.com/shorts/EiiGF3bSrPo",
        "https://www.youtube.com/shorts/DthW2UpUc9g", "https://www.youtube.com/shorts/_rjlAgnkNKo",
        "https://www.youtube.com/shorts/6kIo_Ldc5NQ", "https://www.youtube.com/shorts/whWFhs0Mge8",
        "https://www.youtube.com/shorts/ITX00QeOF1M", "https://www.youtube.com/shorts/uSQtDb1ADvc",
        "https://www.youtube.com/shorts/bCZx5heqRo0", "https://www.youtube.com/shorts/h-mcNDhBkWA",
        "https://www.youtube.com/shorts/eOGYtACgLiA", "https://www.youtube.com/shorts/EDGE0tRCnK0",
        "https://www.youtube.com/shorts/C7nYvVXeCKU", "https://www.youtube.com/shorts/EHPlGhkLA4o",
        "https://www.youtube.com/shorts/NveOTTwDTDE", "https://www.youtube.com/shorts/Irnw4yQfz9Y",
        "https://www.youtube.com/shorts/pw7BSgnjezM", "https://www.youtube.com/shorts/vcH97LpLaCc",
        "https://www.youtube.com/shorts/G-t7U4gRkf4", "https://www.youtube.com/shorts/oUxRVxKvfBM",
        "https://www.youtube.com/shorts/qu9tboBF_Gk", "https://www.youtube.com/shorts/p0zn7DO9thA",
        "https://www.youtube.com/shorts/CNtVtN2Gy_0", "https://www.youtube.com/shorts/elKb23DZSQ4",
        "https://www.youtube.com/shorts/BmC3tEpAHZw", "https://www.youtube.com/shorts/htif81r-s1U",
        "https://www.youtube.com/shorts/63JTVZoq9qc", "https://www.youtube.com/shorts/a8AHe4jzoKg",
        "https://www.youtube.com/shorts/F5inROlhuIg", "https://www.youtube.com/shorts/hCAYcXr6RU8",
        "https://www.youtube.com/shorts/-DHxqIBLGZ8", "https://www.youtube.com/shorts/ryrj1ryBquQ",
        "https://www.youtube.com/shorts/et_YDCatnKQ", "https://www.youtube.com/shorts/RCra6luEZ9o",
        "https://www.youtube.com/shorts/UyoNAXNdeWE", "https://www.youtube.com/shorts/t-RUUTeuu7E",
        "https://www.youtube.com/shorts/YrOp5gQwN5E", "https://www.youtube.com/shorts/P5vGVIbgSWI",
        "https://www.youtube.com/shorts/F8ErMs_hOno", "https://www.youtube.com/shorts/RjbxfGjy5vA",
        "https://www.youtube.com/shorts/BxdHBVUWHjY", "https://www.youtube.com/shorts/oCAzdFH6rNA",
        "https://www.youtube.com/shorts/Dzf4kUxAujw", "https://www.youtube.com/shorts/SfVNHjm4smg",
        "https://www.youtube.com/shorts/w3CQV1sCPSw", "https://www.youtube.com/shorts/nD6imoVW9K0",
        "https://www.youtube.com/shorts/W8uBeUdEw98", "https://www.youtube.com/shorts/-hYmZasoSjI",
        "https://www.youtube.com/shorts/1eCyua6DF_A", "https://www.youtube.com/shorts/nrK-FOuesNQ",
        "https://www.youtube.com/shorts/OrrtVim8B2c", "https://www.youtube.com/shorts/SHd17-Rmi_4",
        "https://www.youtube.com/shorts/WRj4sQHM1WE", "https://www.youtube.com/shorts/ILezJDSeLZE",
        "https://www.youtube.com/shorts/RB6lKAqPj88", "https://www.youtube.com/shorts/74e5dfiPLsU",
        "https://www.youtube.com/shorts/tLqi7rsLdlY", "https://www.youtube.com/shorts/_ywuywP0NbY",
        "https://www.youtube.com/shorts/xgDZZ0m-kRU", "https://www.youtube.com/shorts/Irlg9_4ZpdI",
        "https://www.youtube.com/shorts/WhJPN6q9n6w", "https://www.youtube.com/shorts/nDqYR0b4_tU",
        "https://www.youtube.com/shorts/kSarqAUJh74", "https://www.youtube.com/shorts/jWj8or4Jvcc",
        "https://www.youtube.com/shorts/_6RZthOyyl8", "https://www.youtube.com/shorts/EkMSZxzq9fs",
        "https://www.youtube.com/shorts/uRyln3hhk1k", "https://www.youtube.com/shorts/Ms_sMvem7x8",
        "https://www.youtube.com/shorts/nqFqRBSRDkA", "https://www.youtube.com/shorts/WS8KQHFpPH8",
        "https://www.youtube.com/shorts/dH8KxdNP_F0", "https://www.youtube.com/shorts/oB5kKrik_9s",
        "https://www.youtube.com/shorts/EDIfre8RYa8", "https://www.youtube.com/shorts/xWwk_ShZuVg",
        "https://www.youtube.com/shorts/Yi1C0-Au_wk", "https://www.youtube.com/shorts/IdB7wVWgUc4",
        "https://www.youtube.com/shorts/h84a35i7OVg", "https://www.youtube.com/shorts/zbbOw1KBpD8",
        "https://www.youtube.com/shorts/BOqrg_61v5U", "https://www.youtube.com/shorts/SGDpTrNshMQ",
        "https://www.youtube.com/shorts/V1Rt8gzu2Rk", "https://www.youtube.com/shorts/Opx-QqApmqI",
        "https://www.youtube.com/shorts/xuKr9VZzetk", "https://www.youtube.com/shorts/Y7l2qCGIxiY",
        "https://www.youtube.com/shorts/RY7OaIgxp_k", "https://www.youtube.com/shorts/2wuLgrsapB0",
        "https://www.youtube.com/shorts/fCtkFV78AFY", "https://www.youtube.com/shorts/2TQYfUwrlsU",
        "https://www.youtube.com/shorts/M-Tx9pJsa44", "https://www.youtube.com/shorts/pg5i45z2vPU",
        "https://www.youtube.com/shorts/RnYyBImejbE", "https://www.youtube.com/shorts/19hmyD0p4sM",
        "https://www.youtube.com/shorts/Ecv1PciarsU", "https://www.youtube.com/shorts/xbdXEl_Ollo",
        "https://www.youtube.com/shorts/sF00ojHAWcU", "https://www.youtube.com/shorts/C163ySA6XuA",
        "https://www.youtube.com/shorts/ek-ZUGDKWOw", "https://www.youtube.com/shorts/gLAOC-dv_uk",
        "https://www.youtube.com/shorts/fPmTvwsd3KA", "https://www.youtube.com/shorts/bRKXOTGtojA",
        "https://www.youtube.com/shorts/hNEzR_HxBGs", "https://www.youtube.com/shorts/LFTAYf5tWPI",
        "https://www.youtube.com/shorts/9Lz65Cc7Jpg", "https://www.youtube.com/shorts/F8jjsFpdCpc",
        "https://www.youtube.com/shorts/_6Q129-Ctkc", "https://www.youtube.com/shorts/N_EYZ8FL4xQ",
        "https://www.youtube.com/shorts/onx29vZYq24", "https://www.youtube.com/shorts/zhbqKpwig44",
        "https://www.youtube.com/shorts/ztzlNDLRN1s", "https://www.youtube.com/shorts/loA1UEej6f4",
        "https://www.youtube.com/shorts/zTg0k0ieSLg", "https://www.youtube.com/shorts/4qiZb4qqn3Y",
        "https://www.youtube.com/shorts/l5BqFA3TtSU", "https://www.youtube.com/shorts/jyqZj9LCMLU",
        "https://www.youtube.com/shorts/kNS--Vjrr4s", "https://www.youtube.com/shorts/02wlIRFJGHI",
        "https://www.youtube.com/shorts/eP1T2MjgMS8", "https://www.youtube.com/shorts/v0-lEz3fFME",
    ]
}
